package types

import "time"

// SnapshotConfig carries the parameters for creating a snapshot.
// The hypervisor fills ID, Image, ImageBlobIDs, Hypervisor, and resource fields; the CLI adds Name and Description.
type SnapshotConfig struct {
	ID           string              `json:"id,omitempty"` // generated by the hypervisor during Snapshot()
	Name         string              `json:"name"`
	Description  string              `json:"description,omitempty"`
	Image        string              `json:"image,omitempty"`          // source image reference (e.g. "ubuntu:22.04")
	ImageBlobIDs map[string]struct{} `json:"image_blob_ids,omitempty"` // blob hex set for GC pinning
	Hypervisor   string              `json:"hypervisor,omitempty"`     // originating backend ("cloud-hypervisor" or "firecracker")

	// Original VM resource config, populated during snapshot creation.
	// Used by clone for parameter inheritance and validation.
	CPU           int    `json:"cpu,omitempty"`
	Memory        int64  `json:"memory,omitempty"`  // bytes
	Storage       int64  `json:"storage,omitempty"` // bytes
	NICs          int    `json:"nics,omitempty"`
	QueueSize     int    `json:"queue_size,omitempty"`
	DiskQueueSize int    `json:"disk_queue_size,omitempty"`
	Network       string `json:"network,omitempty"`
	NoDirectIO    bool   `json:"no_direct_io,omitempty"`
	Windows       bool   `json:"windows,omitempty"`
}

// Snapshot is the public record for a snapshot.
type Snapshot struct {
	SnapshotConfig
	CreatedAt time.Time `json:"created_at"`
}

// SnapshotExport is the envelope written as snapshot.json inside an export archive.
type SnapshotExport struct {
	Version int            `json:"version"`
	Config  SnapshotConfig `json:"config"`
}
