// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"sync"

	"github.com/projecteru2/cocoon/gc"
	"github.com/projecteru2/cocoon/network"
	"github.com/projecteru2/cocoon/types"
)

// Ensure, that NetworkMock does implement network.Network.
// If this is not the case, regenerate this file with moq.
var _ network.Network = &NetworkMock{}

// NetworkMock is a mock implementation of network.Network.
//
//	func TestSomethingThatUsesNetwork(t *testing.T) {
//
//		// make and configure a mocked network.Network
//		mockedNetwork := &NetworkMock{
//			ConfigFunc: func(ctx context.Context, vmID string, numNICs int, vmCfg *types.VMConfig, existing ...*types.NetworkConfig) ([]*types.NetworkConfig, error) {
//				panic("mock out the Config method")
//			},
//			DeleteFunc: func(contextMoqParam context.Context, strings []string) ([]string, error) {
//				panic("mock out the Delete method")
//			},
//			InspectFunc: func(contextMoqParam context.Context, s string) (*types.Network, error) {
//				panic("mock out the Inspect method")
//			},
//			ListFunc: func(contextMoqParam context.Context) ([]*types.Network, error) {
//				panic("mock out the List method")
//			},
//			RegisterGCFunc: func(orchestrator *gc.Orchestrator)  {
//				panic("mock out the RegisterGC method")
//			},
//			TypeFunc: func() string {
//				panic("mock out the Type method")
//			},
//			VerifyFunc: func(ctx context.Context, vmID string) error {
//				panic("mock out the Verify method")
//			},
//		}
//
//		// use mockedNetwork in code that requires network.Network
//		// and then make assertions.
//
//	}
type NetworkMock struct {
	// ConfigFunc mocks the Config method.
	ConfigFunc func(ctx context.Context, vmID string, numNICs int, vmCfg *types.VMConfig, existing ...*types.NetworkConfig) ([]*types.NetworkConfig, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(contextMoqParam context.Context, strings []string) ([]string, error)

	// InspectFunc mocks the Inspect method.
	InspectFunc func(contextMoqParam context.Context, s string) (*types.Network, error)

	// ListFunc mocks the List method.
	ListFunc func(contextMoqParam context.Context) ([]*types.Network, error)

	// RegisterGCFunc mocks the RegisterGC method.
	RegisterGCFunc func(orchestrator *gc.Orchestrator)

	// TypeFunc mocks the Type method.
	TypeFunc func() string

	// VerifyFunc mocks the Verify method.
	VerifyFunc func(ctx context.Context, vmID string) error

	// calls tracks calls to the methods.
	calls struct {
		// Config holds details about calls to the Config method.
		Config []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VmID is the vmID argument value.
			VmID string
			// NumNICs is the numNICs argument value.
			NumNICs int
			// VmCfg is the vmCfg argument value.
			VmCfg *types.VMConfig
			// Existing is the existing argument value.
			Existing []*types.NetworkConfig
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Strings is the strings argument value.
			Strings []string
		}
		// Inspect holds details about calls to the Inspect method.
		Inspect []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// List holds details about calls to the List method.
		List []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// RegisterGC holds details about calls to the RegisterGC method.
		RegisterGC []struct {
			// Orchestrator is the orchestrator argument value.
			Orchestrator *gc.Orchestrator
		}
		// Type holds details about calls to the Type method.
		Type []struct{}
		// Verify holds details about calls to the Verify method.
		Verify []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VmID is the vmID argument value.
			VmID string
		}
	}
	lockConfig     sync.RWMutex
	lockDelete     sync.RWMutex
	lockInspect    sync.RWMutex
	lockList       sync.RWMutex
	lockRegisterGC sync.RWMutex
	lockType       sync.RWMutex
	lockVerify     sync.RWMutex
}

// Config calls ConfigFunc.
func (mock *NetworkMock) Config(ctx context.Context, vmID string, numNICs int, vmCfg *types.VMConfig, existing ...*types.NetworkConfig) ([]*types.NetworkConfig, error) {
	if mock.ConfigFunc == nil {
		panic("NetworkMock.ConfigFunc: method is nil but Network.Config was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		VmID     string
		NumNICs  int
		VmCfg    *types.VMConfig
		Existing []*types.NetworkConfig
	}{
		Ctx:      ctx,
		VmID:     vmID,
		NumNICs:  numNICs,
		VmCfg:    vmCfg,
		Existing: existing,
	}
	mock.lockConfig.Lock()
	mock.calls.Config = append(mock.calls.Config, callInfo)
	mock.lockConfig.Unlock()
	return mock.ConfigFunc(ctx, vmID, numNICs, vmCfg, existing...)
}

// ConfigCalls gets all the calls that were made to Config.
// Check the length with:
//
//	len(mockedNetwork.ConfigCalls())
func (mock *NetworkMock) ConfigCalls() []struct {
	Ctx      context.Context
	VmID     string
	NumNICs  int
	VmCfg    *types.VMConfig
	Existing []*types.NetworkConfig
} {
	var calls []struct {
		Ctx      context.Context
		VmID     string
		NumNICs  int
		VmCfg    *types.VMConfig
		Existing []*types.NetworkConfig
	}
	mock.lockConfig.RLock()
	calls = mock.calls.Config
	mock.lockConfig.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *NetworkMock) Delete(contextMoqParam context.Context, strings []string) ([]string, error) {
	if mock.DeleteFunc == nil {
		panic("NetworkMock.DeleteFunc: method is nil but Network.Delete was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Strings         []string
	}{
		ContextMoqParam: contextMoqParam,
		Strings:         strings,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(contextMoqParam, strings)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedNetwork.DeleteCalls())
func (mock *NetworkMock) DeleteCalls() []struct {
	ContextMoqParam context.Context
	Strings         []string
} {
	var calls []struct {
		ContextMoqParam context.Context
		Strings         []string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Inspect calls InspectFunc.
func (mock *NetworkMock) Inspect(contextMoqParam context.Context, s string) (*types.Network, error) {
	if mock.InspectFunc == nil {
		panic("NetworkMock.InspectFunc: method is nil but Network.Inspect was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockInspect.Lock()
	mock.calls.Inspect = append(mock.calls.Inspect, callInfo)
	mock.lockInspect.Unlock()
	return mock.InspectFunc(contextMoqParam, s)
}

// InspectCalls gets all the calls that were made to Inspect.
// Check the length with:
//
//	len(mockedNetwork.InspectCalls())
func (mock *NetworkMock) InspectCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockInspect.RLock()
	calls = mock.calls.Inspect
	mock.lockInspect.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *NetworkMock) List(contextMoqParam context.Context) ([]*types.Network, error) {
	if mock.ListFunc == nil {
		panic("NetworkMock.ListFunc: method is nil but Network.List was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(contextMoqParam)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedNetwork.ListCalls())
func (mock *NetworkMock) ListCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// RegisterGC calls RegisterGCFunc.
func (mock *NetworkMock) RegisterGC(orchestrator *gc.Orchestrator) {
	if mock.RegisterGCFunc == nil {
		panic("NetworkMock.RegisterGCFunc: method is nil but Network.RegisterGC was just called")
	}
	callInfo := struct {
		Orchestrator *gc.Orchestrator
	}{
		Orchestrator: orchestrator,
	}
	mock.lockRegisterGC.Lock()
	mock.calls.RegisterGC = append(mock.calls.RegisterGC, callInfo)
	mock.lockRegisterGC.Unlock()
	mock.RegisterGCFunc(orchestrator)
}

// RegisterGCCalls gets all the calls that were made to RegisterGC.
// Check the length with:
//
//	len(mockedNetwork.RegisterGCCalls())
func (mock *NetworkMock) RegisterGCCalls() []struct {
	Orchestrator *gc.Orchestrator
} {
	var calls []struct {
		Orchestrator *gc.Orchestrator
	}
	mock.lockRegisterGC.RLock()
	calls = mock.calls.RegisterGC
	mock.lockRegisterGC.RUnlock()
	return calls
}

// Type calls TypeFunc.
func (mock *NetworkMock) Type() string {
	if mock.TypeFunc == nil {
		panic("NetworkMock.TypeFunc: method is nil but Network.Type was just called")
	}
	callInfo := struct{}{}
	mock.lockType.Lock()
	mock.calls.Type = append(mock.calls.Type, callInfo)
	mock.lockType.Unlock()
	return mock.TypeFunc()
}

// TypeCalls gets all the calls that were made to Type.
// Check the length with:
//
//	len(mockedNetwork.TypeCalls())
func (mock *NetworkMock) TypeCalls() []struct{} {
	var calls []struct{}
	mock.lockType.RLock()
	calls = mock.calls.Type
	mock.lockType.RUnlock()
	return calls
}

// Verify calls VerifyFunc.
func (mock *NetworkMock) Verify(ctx context.Context, vmID string) error {
	if mock.VerifyFunc == nil {
		panic("NetworkMock.VerifyFunc: method is nil but Network.Verify was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		VmID string
	}{
		Ctx:  ctx,
		VmID: vmID,
	}
	mock.lockVerify.Lock()
	mock.calls.Verify = append(mock.calls.Verify, callInfo)
	mock.lockVerify.Unlock()
	return mock.VerifyFunc(ctx, vmID)
}

// VerifyCalls gets all the calls that were made to Verify.
// Check the length with:
//
//	len(mockedNetwork.VerifyCalls())
func (mock *NetworkMock) VerifyCalls() []struct {
	Ctx  context.Context
	VmID string
} {
	var calls []struct {
		Ctx  context.Context
		VmID string
	}
	mock.lockVerify.RLock()
	calls = mock.calls.Verify
	mock.lockVerify.RUnlock()
	return calls
}
