// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"sync"

	"github.com/projecteru2/cocoon/gc"
	"github.com/projecteru2/cocoon/images"
	"github.com/projecteru2/cocoon/progress"
	"github.com/projecteru2/cocoon/types"
)

// Ensure, that ImagesMock does implement images.Images.
// If this is not the case, regenerate this file with moq.
var _ images.Images = &ImagesMock{}

// ImagesMock is a mock implementation of images.Images.
//
//	func TestSomethingThatUsesImages(t *testing.T) {
//
//		// make and configure a mocked images.Images
//		mockedImages := &ImagesMock{
//			ConfigFunc: func(contextMoqParam context.Context, vMConfigs []*types.VMConfig) ([][]*types.StorageConfig, []*types.BootConfig, error) {
//				panic("mock out the Config method")
//			},
//			DeleteFunc: func(contextMoqParam context.Context, strings []string) ([]string, error) {
//				panic("mock out the Delete method")
//			},
//			ImportFunc: func(ctx context.Context, name string, tracker progress.Tracker, file ...string) error {
//				panic("mock out the Import method")
//			},
//			InspectFunc: func(contextMoqParam context.Context, s string) (*types.Image, error) {
//				panic("mock out the Inspect method")
//			},
//			ListFunc: func(contextMoqParam context.Context) ([]*types.Image, error) {
//				panic("mock out the List method")
//			},
//			PullFunc: func(contextMoqParam context.Context, s string, tracker progress.Tracker) error {
//				panic("mock out the Pull method")
//			},
//			RegisterGCFunc: func(orchestrator *gc.Orchestrator)  {
//				panic("mock out the RegisterGC method")
//			},
//			TypeFunc: func() string {
//				panic("mock out the Type method")
//			},
//		}
//
//		// use mockedImages in code that requires images.Images
//		// and then make assertions.
//
//	}
type ImagesMock struct {
	// ConfigFunc mocks the Config method.
	ConfigFunc func(contextMoqParam context.Context, vMConfigs []*types.VMConfig) ([][]*types.StorageConfig, []*types.BootConfig, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(contextMoqParam context.Context, strings []string) ([]string, error)

	// ImportFunc mocks the Import method.
	ImportFunc func(ctx context.Context, name string, tracker progress.Tracker, file ...string) error

	// InspectFunc mocks the Inspect method.
	InspectFunc func(contextMoqParam context.Context, s string) (*types.Image, error)

	// ListFunc mocks the List method.
	ListFunc func(contextMoqParam context.Context) ([]*types.Image, error)

	// PullFunc mocks the Pull method.
	PullFunc func(contextMoqParam context.Context, s string, tracker progress.Tracker) error

	// RegisterGCFunc mocks the RegisterGC method.
	RegisterGCFunc func(orchestrator *gc.Orchestrator)

	// TypeFunc mocks the Type method.
	TypeFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Config holds details about calls to the Config method.
		Config []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// VMConfigs is the vMConfigs argument value.
			VMConfigs []*types.VMConfig
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Strings is the strings argument value.
			Strings []string
		}
		// Import holds details about calls to the Import method.
		Import []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Tracker is the tracker argument value.
			Tracker progress.Tracker
			// File is the file argument value.
			File []string
		}
		// Inspect holds details about calls to the Inspect method.
		Inspect []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// List holds details about calls to the List method.
		List []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// Pull holds details about calls to the Pull method.
		Pull []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
			// Tracker is the tracker argument value.
			Tracker progress.Tracker
		}
		// RegisterGC holds details about calls to the RegisterGC method.
		RegisterGC []struct {
			// Orchestrator is the orchestrator argument value.
			Orchestrator *gc.Orchestrator
		}
		// Type holds details about calls to the Type method.
		Type []struct{}
	}
	lockConfig     sync.RWMutex
	lockDelete     sync.RWMutex
	lockImport     sync.RWMutex
	lockInspect    sync.RWMutex
	lockList       sync.RWMutex
	lockPull       sync.RWMutex
	lockRegisterGC sync.RWMutex
	lockType       sync.RWMutex
}

// Config calls ConfigFunc.
func (mock *ImagesMock) Config(contextMoqParam context.Context, vMConfigs []*types.VMConfig) ([][]*types.StorageConfig, []*types.BootConfig, error) {
	if mock.ConfigFunc == nil {
		panic("ImagesMock.ConfigFunc: method is nil but Images.Config was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		VMConfigs       []*types.VMConfig
	}{
		ContextMoqParam: contextMoqParam,
		VMConfigs:       vMConfigs,
	}
	mock.lockConfig.Lock()
	mock.calls.Config = append(mock.calls.Config, callInfo)
	mock.lockConfig.Unlock()
	return mock.ConfigFunc(contextMoqParam, vMConfigs)
}

// ConfigCalls gets all the calls that were made to Config.
// Check the length with:
//
//	len(mockedImages.ConfigCalls())
func (mock *ImagesMock) ConfigCalls() []struct {
	ContextMoqParam context.Context
	VMConfigs       []*types.VMConfig
} {
	var calls []struct {
		ContextMoqParam context.Context
		VMConfigs       []*types.VMConfig
	}
	mock.lockConfig.RLock()
	calls = mock.calls.Config
	mock.lockConfig.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *ImagesMock) Delete(contextMoqParam context.Context, strings []string) ([]string, error) {
	if mock.DeleteFunc == nil {
		panic("ImagesMock.DeleteFunc: method is nil but Images.Delete was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Strings         []string
	}{
		ContextMoqParam: contextMoqParam,
		Strings:         strings,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(contextMoqParam, strings)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedImages.DeleteCalls())
func (mock *ImagesMock) DeleteCalls() []struct {
	ContextMoqParam context.Context
	Strings         []string
} {
	var calls []struct {
		ContextMoqParam context.Context
		Strings         []string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Import calls ImportFunc.
func (mock *ImagesMock) Import(ctx context.Context, name string, tracker progress.Tracker, file ...string) error {
	if mock.ImportFunc == nil {
		panic("ImagesMock.ImportFunc: method is nil but Images.Import was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Name    string
		Tracker progress.Tracker
		File    []string
	}{
		Ctx:     ctx,
		Name:    name,
		Tracker: tracker,
		File:    file,
	}
	mock.lockImport.Lock()
	mock.calls.Import = append(mock.calls.Import, callInfo)
	mock.lockImport.Unlock()
	return mock.ImportFunc(ctx, name, tracker, file...)
}

// ImportCalls gets all the calls that were made to Import.
// Check the length with:
//
//	len(mockedImages.ImportCalls())
func (mock *ImagesMock) ImportCalls() []struct {
	Ctx     context.Context
	Name    string
	Tracker progress.Tracker
	File    []string
} {
	var calls []struct {
		Ctx     context.Context
		Name    string
		Tracker progress.Tracker
		File    []string
	}
	mock.lockImport.RLock()
	calls = mock.calls.Import
	mock.lockImport.RUnlock()
	return calls
}

// Inspect calls InspectFunc.
func (mock *ImagesMock) Inspect(contextMoqParam context.Context, s string) (*types.Image, error) {
	if mock.InspectFunc == nil {
		panic("ImagesMock.InspectFunc: method is nil but Images.Inspect was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockInspect.Lock()
	mock.calls.Inspect = append(mock.calls.Inspect, callInfo)
	mock.lockInspect.Unlock()
	return mock.InspectFunc(contextMoqParam, s)
}

// InspectCalls gets all the calls that were made to Inspect.
// Check the length with:
//
//	len(mockedImages.InspectCalls())
func (mock *ImagesMock) InspectCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockInspect.RLock()
	calls = mock.calls.Inspect
	mock.lockInspect.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *ImagesMock) List(contextMoqParam context.Context) ([]*types.Image, error) {
	if mock.ListFunc == nil {
		panic("ImagesMock.ListFunc: method is nil but Images.List was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(contextMoqParam)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedImages.ListCalls())
func (mock *ImagesMock) ListCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Pull calls PullFunc.
func (mock *ImagesMock) Pull(contextMoqParam context.Context, s string, tracker progress.Tracker) error {
	if mock.PullFunc == nil {
		panic("ImagesMock.PullFunc: method is nil but Images.Pull was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
		Tracker         progress.Tracker
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
		Tracker:         tracker,
	}
	mock.lockPull.Lock()
	mock.calls.Pull = append(mock.calls.Pull, callInfo)
	mock.lockPull.Unlock()
	return mock.PullFunc(contextMoqParam, s, tracker)
}

// PullCalls gets all the calls that were made to Pull.
// Check the length with:
//
//	len(mockedImages.PullCalls())
func (mock *ImagesMock) PullCalls() []struct {
	ContextMoqParam context.Context
	S               string
	Tracker         progress.Tracker
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
		Tracker         progress.Tracker
	}
	mock.lockPull.RLock()
	calls = mock.calls.Pull
	mock.lockPull.RUnlock()
	return calls
}

// RegisterGC calls RegisterGCFunc.
func (mock *ImagesMock) RegisterGC(orchestrator *gc.Orchestrator) {
	if mock.RegisterGCFunc == nil {
		panic("ImagesMock.RegisterGCFunc: method is nil but Images.RegisterGC was just called")
	}
	callInfo := struct {
		Orchestrator *gc.Orchestrator
	}{
		Orchestrator: orchestrator,
	}
	mock.lockRegisterGC.Lock()
	mock.calls.RegisterGC = append(mock.calls.RegisterGC, callInfo)
	mock.lockRegisterGC.Unlock()
	mock.RegisterGCFunc(orchestrator)
}

// RegisterGCCalls gets all the calls that were made to RegisterGC.
// Check the length with:
//
//	len(mockedImages.RegisterGCCalls())
func (mock *ImagesMock) RegisterGCCalls() []struct {
	Orchestrator *gc.Orchestrator
} {
	var calls []struct {
		Orchestrator *gc.Orchestrator
	}
	mock.lockRegisterGC.RLock()
	calls = mock.calls.RegisterGC
	mock.lockRegisterGC.RUnlock()
	return calls
}

// Type calls TypeFunc.
func (mock *ImagesMock) Type() string {
	if mock.TypeFunc == nil {
		panic("ImagesMock.TypeFunc: method is nil but Images.Type was just called")
	}
	callInfo := struct{}{}
	mock.lockType.Lock()
	mock.calls.Type = append(mock.calls.Type, callInfo)
	mock.lockType.Unlock()
	return mock.TypeFunc()
}

// TypeCalls gets all the calls that were made to Type.
// Check the length with:
//
//	len(mockedImages.TypeCalls())
func (mock *ImagesMock) TypeCalls() []struct{} {
	var calls []struct{}
	mock.lockType.RLock()
	calls = mock.calls.Type
	mock.lockType.RUnlock()
	return calls
}
