// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"io"
	"sync"

	"github.com/projecteru2/cocoon/gc"
	"github.com/projecteru2/cocoon/snapshot"
	"github.com/projecteru2/cocoon/types"
)

// Ensure, that SnapshotMock does implement snapshot.Snapshot.
// If this is not the case, regenerate this file with moq.
var _ snapshot.Snapshot = &SnapshotMock{}

// SnapshotMock is a mock implementation of snapshot.Snapshot.
//
//	func TestSomethingThatUsesSnapshot(t *testing.T) {
//
//		// make and configure a mocked snapshot.Snapshot
//		mockedSnapshot := &SnapshotMock{
//			CreateFunc: func(ctx context.Context, cfg *types.SnapshotConfig, stream io.Reader) (string, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, refs []string) ([]string, error) {
//				panic("mock out the Delete method")
//			},
//			InspectFunc: func(ctx context.Context, ref string) (*types.Snapshot, error) {
//				panic("mock out the Inspect method")
//			},
//			ListFunc: func(ctx context.Context) ([]*types.Snapshot, error) {
//				panic("mock out the List method")
//			},
//			RegisterGCFunc: func(orchestrator *gc.Orchestrator)  {
//				panic("mock out the RegisterGC method")
//			},
//			RestoreFunc: func(ctx context.Context, ref string) (*types.SnapshotConfig, io.ReadCloser, error) {
//				panic("mock out the Restore method")
//			},
//			TypeFunc: func() string {
//				panic("mock out the Type method")
//			},
//		}
//
//		// use mockedSnapshot in code that requires snapshot.Snapshot
//		// and then make assertions.
//
//	}
type SnapshotMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, cfg *types.SnapshotConfig, stream io.Reader) (string, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, refs []string) ([]string, error)

	// InspectFunc mocks the Inspect method.
	InspectFunc func(ctx context.Context, ref string) (*types.Snapshot, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]*types.Snapshot, error)

	// RegisterGCFunc mocks the RegisterGC method.
	RegisterGCFunc func(orchestrator *gc.Orchestrator)

	// RestoreFunc mocks the Restore method.
	RestoreFunc func(ctx context.Context, ref string) (*types.SnapshotConfig, io.ReadCloser, error)

	// TypeFunc mocks the Type method.
	TypeFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cfg is the cfg argument value.
			Cfg *types.SnapshotConfig
			// Stream is the stream argument value.
			Stream io.Reader
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Refs is the refs argument value.
			Refs []string
		}
		// Inspect holds details about calls to the Inspect method.
		Inspect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// RegisterGC holds details about calls to the RegisterGC method.
		RegisterGC []struct {
			// Orchestrator is the orchestrator argument value.
			Orchestrator *gc.Orchestrator
		}
		// Restore holds details about calls to the Restore method.
		Restore []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
		}
		// Type holds details about calls to the Type method.
		Type []struct{}
	}
	lockCreate     sync.RWMutex
	lockDelete     sync.RWMutex
	lockInspect    sync.RWMutex
	lockList       sync.RWMutex
	lockRegisterGC sync.RWMutex
	lockRestore    sync.RWMutex
	lockType       sync.RWMutex
}

// Create calls CreateFunc.
func (mock *SnapshotMock) Create(ctx context.Context, cfg *types.SnapshotConfig, stream io.Reader) (string, error) {
	if mock.CreateFunc == nil {
		panic("SnapshotMock.CreateFunc: method is nil but Snapshot.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Cfg    *types.SnapshotConfig
		Stream io.Reader
	}{
		Ctx:    ctx,
		Cfg:    cfg,
		Stream: stream,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, cfg, stream)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedSnapshot.CreateCalls())
func (mock *SnapshotMock) CreateCalls() []struct {
	Ctx    context.Context
	Cfg    *types.SnapshotConfig
	Stream io.Reader
} {
	var calls []struct {
		Ctx    context.Context
		Cfg    *types.SnapshotConfig
		Stream io.Reader
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *SnapshotMock) Delete(ctx context.Context, refs []string) ([]string, error) {
	if mock.DeleteFunc == nil {
		panic("SnapshotMock.DeleteFunc: method is nil but Snapshot.Delete was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Refs []string
	}{
		Ctx:  ctx,
		Refs: refs,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, refs)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedSnapshot.DeleteCalls())
func (mock *SnapshotMock) DeleteCalls() []struct {
	Ctx  context.Context
	Refs []string
} {
	var calls []struct {
		Ctx  context.Context
		Refs []string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Inspect calls InspectFunc.
func (mock *SnapshotMock) Inspect(ctx context.Context, ref string) (*types.Snapshot, error) {
	if mock.InspectFunc == nil {
		panic("SnapshotMock.InspectFunc: method is nil but Snapshot.Inspect was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref string
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockInspect.Lock()
	mock.calls.Inspect = append(mock.calls.Inspect, callInfo)
	mock.lockInspect.Unlock()
	return mock.InspectFunc(ctx, ref)
}

// InspectCalls gets all the calls that were made to Inspect.
// Check the length with:
//
//	len(mockedSnapshot.InspectCalls())
func (mock *SnapshotMock) InspectCalls() []struct {
	Ctx context.Context
	Ref string
} {
	var calls []struct {
		Ctx context.Context
		Ref string
	}
	mock.lockInspect.RLock()
	calls = mock.calls.Inspect
	mock.lockInspect.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *SnapshotMock) List(ctx context.Context) ([]*types.Snapshot, error) {
	if mock.ListFunc == nil {
		panic("SnapshotMock.ListFunc: method is nil but Snapshot.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedSnapshot.ListCalls())
func (mock *SnapshotMock) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// RegisterGC calls RegisterGCFunc.
func (mock *SnapshotMock) RegisterGC(orchestrator *gc.Orchestrator) {
	if mock.RegisterGCFunc == nil {
		panic("SnapshotMock.RegisterGCFunc: method is nil but Snapshot.RegisterGC was just called")
	}
	callInfo := struct {
		Orchestrator *gc.Orchestrator
	}{
		Orchestrator: orchestrator,
	}
	mock.lockRegisterGC.Lock()
	mock.calls.RegisterGC = append(mock.calls.RegisterGC, callInfo)
	mock.lockRegisterGC.Unlock()
	mock.RegisterGCFunc(orchestrator)
}

// RegisterGCCalls gets all the calls that were made to RegisterGC.
// Check the length with:
//
//	len(mockedSnapshot.RegisterGCCalls())
func (mock *SnapshotMock) RegisterGCCalls() []struct {
	Orchestrator *gc.Orchestrator
} {
	var calls []struct {
		Orchestrator *gc.Orchestrator
	}
	mock.lockRegisterGC.RLock()
	calls = mock.calls.RegisterGC
	mock.lockRegisterGC.RUnlock()
	return calls
}

// Restore calls RestoreFunc.
func (mock *SnapshotMock) Restore(ctx context.Context, ref string) (*types.SnapshotConfig, io.ReadCloser, error) {
	if mock.RestoreFunc == nil {
		panic("SnapshotMock.RestoreFunc: method is nil but Snapshot.Restore was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref string
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockRestore.Lock()
	mock.calls.Restore = append(mock.calls.Restore, callInfo)
	mock.lockRestore.Unlock()
	return mock.RestoreFunc(ctx, ref)
}

// RestoreCalls gets all the calls that were made to Restore.
// Check the length with:
//
//	len(mockedSnapshot.RestoreCalls())
func (mock *SnapshotMock) RestoreCalls() []struct {
	Ctx context.Context
	Ref string
} {
	var calls []struct {
		Ctx context.Context
		Ref string
	}
	mock.lockRestore.RLock()
	calls = mock.calls.Restore
	mock.lockRestore.RUnlock()
	return calls
}

// Type calls TypeFunc.
func (mock *SnapshotMock) Type() string {
	if mock.TypeFunc == nil {
		panic("SnapshotMock.TypeFunc: method is nil but Snapshot.Type was just called")
	}
	callInfo := struct{}{}
	mock.lockType.Lock()
	mock.calls.Type = append(mock.calls.Type, callInfo)
	mock.lockType.Unlock()
	return mock.TypeFunc()
}

// TypeCalls gets all the calls that were made to Type.
// Check the length with:
//
//	len(mockedSnapshot.TypeCalls())
func (mock *SnapshotMock) TypeCalls() []struct{} {
	var calls []struct{}
	mock.lockType.RLock()
	calls = mock.calls.Type
	mock.lockType.RUnlock()
	return calls
}
