// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"io"
	"sync"

	"github.com/projecteru2/cocoon/gc"
	"github.com/projecteru2/cocoon/hypervisor"
	"github.com/projecteru2/cocoon/types"
)

// Ensure, that HypervisorMock does implement hypervisor.Hypervisor.
// If this is not the case, regenerate this file with moq.
var _ hypervisor.Hypervisor = &HypervisorMock{}

// HypervisorMock is a mock implementation of hypervisor.Hypervisor.
//
//	func TestSomethingThatUsesHypervisor(t *testing.T) {
//
//		// make and configure a mocked hypervisor.Hypervisor
//		mockedHypervisor := &HypervisorMock{
//			CloneFunc: func(ctx context.Context, vmID string, vmCfg *types.VMConfig, networkConfigs []*types.NetworkConfig, snapshotConfig *types.SnapshotConfig, snapshot io.Reader) (*types.VM, error) {
//				panic("mock out the Clone method")
//			},
//			ConsoleFunc: func(ctx context.Context, ref string) (io.ReadWriteCloser, error) {
//				panic("mock out the Console method")
//			},
//			CreateFunc: func(ctx context.Context, vmID string, vmCfg *types.VMConfig, storage []*types.StorageConfig, network []*types.NetworkConfig, boot *types.BootConfig) (*types.VM, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, refs []string, force bool) ([]string, error) {
//				panic("mock out the Delete method")
//			},
//			InspectFunc: func(ctx context.Context, ref string) (*types.VM, error) {
//				panic("mock out the Inspect method")
//			},
//			ListFunc: func(contextMoqParam context.Context) ([]*types.VM, error) {
//				panic("mock out the List method")
//			},
//			RegisterGCFunc: func(orchestrator *gc.Orchestrator)  {
//				panic("mock out the RegisterGC method")
//			},
//			RestoreFunc: func(ctx context.Context, vmRef string, vmCfg *types.VMConfig, snapshot io.Reader) (*types.VM, error) {
//				panic("mock out the Restore method")
//			},
//			SnapshotFunc: func(ctx context.Context, ref string) (*types.SnapshotConfig, io.ReadCloser, error) {
//				panic("mock out the Snapshot method")
//			},
//			StartFunc: func(ctx context.Context, refs []string) ([]string, error) {
//				panic("mock out the Start method")
//			},
//			StopFunc: func(ctx context.Context, refs []string) ([]string, error) {
//				panic("mock out the Stop method")
//			},
//			TypeFunc: func() string {
//				panic("mock out the Type method")
//			},
//		}
//
//		// use mockedHypervisor in code that requires hypervisor.Hypervisor
//		// and then make assertions.
//
//	}
type HypervisorMock struct {
	// CloneFunc mocks the Clone method.
	CloneFunc func(ctx context.Context, vmID string, vmCfg *types.VMConfig, networkConfigs []*types.NetworkConfig, snapshotConfig *types.SnapshotConfig, snapshot io.Reader) (*types.VM, error)

	// ConsoleFunc mocks the Console method.
	ConsoleFunc func(ctx context.Context, ref string) (io.ReadWriteCloser, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, vmID string, vmCfg *types.VMConfig, storage []*types.StorageConfig, network []*types.NetworkConfig, boot *types.BootConfig) (*types.VM, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, refs []string, force bool) ([]string, error)

	// InspectFunc mocks the Inspect method.
	InspectFunc func(ctx context.Context, ref string) (*types.VM, error)

	// ListFunc mocks the List method.
	ListFunc func(contextMoqParam context.Context) ([]*types.VM, error)

	// RegisterGCFunc mocks the RegisterGC method.
	RegisterGCFunc func(orchestrator *gc.Orchestrator)

	// RestoreFunc mocks the Restore method.
	RestoreFunc func(ctx context.Context, vmRef string, vmCfg *types.VMConfig, snapshot io.Reader) (*types.VM, error)

	// SnapshotFunc mocks the Snapshot method.
	SnapshotFunc func(ctx context.Context, ref string) (*types.SnapshotConfig, io.ReadCloser, error)

	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context, refs []string) ([]string, error)

	// StopFunc mocks the Stop method.
	StopFunc func(ctx context.Context, refs []string) ([]string, error)

	// TypeFunc mocks the Type method.
	TypeFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Clone holds details about calls to the Clone method.
		Clone []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VmID is the vmID argument value.
			VmID string
			// VmCfg is the vmCfg argument value.
			VmCfg *types.VMConfig
			// NetworkConfigs is the networkConfigs argument value.
			NetworkConfigs []*types.NetworkConfig
			// SnapshotConfig is the snapshotConfig argument value.
			SnapshotConfig *types.SnapshotConfig
			// Snapshot is the snapshot argument value.
			Snapshot io.Reader
		}
		// Console holds details about calls to the Console method.
		Console []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VmID is the vmID argument value.
			VmID string
			// VmCfg is the vmCfg argument value.
			VmCfg *types.VMConfig
			// Storage is the storage argument value.
			Storage []*types.StorageConfig
			// Network is the network argument value.
			Network []*types.NetworkConfig
			// Boot is the boot argument value.
			Boot *types.BootConfig
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Refs is the refs argument value.
			Refs []string
			// Force is the force argument value.
			Force bool
		}
		// Inspect holds details about calls to the Inspect method.
		Inspect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
		}
		// List holds details about calls to the List method.
		List []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// RegisterGC holds details about calls to the RegisterGC method.
		RegisterGC []struct {
			// Orchestrator is the orchestrator argument value.
			Orchestrator *gc.Orchestrator
		}
		// Restore holds details about calls to the Restore method.
		Restore []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VmRef is the vmRef argument value.
			VmRef string
			// VmCfg is the vmCfg argument value.
			VmCfg *types.VMConfig
			// Snapshot is the snapshot argument value.
			Snapshot io.Reader
		}
		// Snapshot holds details about calls to the Snapshot method.
		Snapshot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Refs is the refs argument value.
			Refs []string
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Refs is the refs argument value.
			Refs []string
		}
		// Type holds details about calls to the Type method.
		Type []struct{}
	}
	lockClone      sync.RWMutex
	lockConsole    sync.RWMutex
	lockCreate     sync.RWMutex
	lockDelete     sync.RWMutex
	lockInspect    sync.RWMutex
	lockList       sync.RWMutex
	lockRegisterGC sync.RWMutex
	lockRestore    sync.RWMutex
	lockSnapshot   sync.RWMutex
	lockStart      sync.RWMutex
	lockStop       sync.RWMutex
	lockType       sync.RWMutex
}

// Clone calls CloneFunc.
func (mock *HypervisorMock) Clone(ctx context.Context, vmID string, vmCfg *types.VMConfig, networkConfigs []*types.NetworkConfig, snapshotConfig *types.SnapshotConfig, snapshot io.Reader) (*types.VM, error) {
	if mock.CloneFunc == nil {
		panic("HypervisorMock.CloneFunc: method is nil but Hypervisor.Clone was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		VmID           string
		VmCfg          *types.VMConfig
		NetworkConfigs []*types.NetworkConfig
		SnapshotConfig *types.SnapshotConfig
		Snapshot       io.Reader
	}{
		Ctx:            ctx,
		VmID:           vmID,
		VmCfg:          vmCfg,
		NetworkConfigs: networkConfigs,
		SnapshotConfig: snapshotConfig,
		Snapshot:       snapshot,
	}
	mock.lockClone.Lock()
	mock.calls.Clone = append(mock.calls.Clone, callInfo)
	mock.lockClone.Unlock()
	return mock.CloneFunc(ctx, vmID, vmCfg, networkConfigs, snapshotConfig, snapshot)
}

// CloneCalls gets all the calls that were made to Clone.
// Check the length with:
//
//	len(mockedHypervisor.CloneCalls())
func (mock *HypervisorMock) CloneCalls() []struct {
	Ctx            context.Context
	VmID           string
	VmCfg          *types.VMConfig
	NetworkConfigs []*types.NetworkConfig
	SnapshotConfig *types.SnapshotConfig
	Snapshot       io.Reader
} {
	var calls []struct {
		Ctx            context.Context
		VmID           string
		VmCfg          *types.VMConfig
		NetworkConfigs []*types.NetworkConfig
		SnapshotConfig *types.SnapshotConfig
		Snapshot       io.Reader
	}
	mock.lockClone.RLock()
	calls = mock.calls.Clone
	mock.lockClone.RUnlock()
	return calls
}

// Console calls ConsoleFunc.
func (mock *HypervisorMock) Console(ctx context.Context, ref string) (io.ReadWriteCloser, error) {
	if mock.ConsoleFunc == nil {
		panic("HypervisorMock.ConsoleFunc: method is nil but Hypervisor.Console was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref string
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockConsole.Lock()
	mock.calls.Console = append(mock.calls.Console, callInfo)
	mock.lockConsole.Unlock()
	return mock.ConsoleFunc(ctx, ref)
}

// ConsoleCalls gets all the calls that were made to Console.
// Check the length with:
//
//	len(mockedHypervisor.ConsoleCalls())
func (mock *HypervisorMock) ConsoleCalls() []struct {
	Ctx context.Context
	Ref string
} {
	var calls []struct {
		Ctx context.Context
		Ref string
	}
	mock.lockConsole.RLock()
	calls = mock.calls.Console
	mock.lockConsole.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *HypervisorMock) Create(ctx context.Context, vmID string, vmCfg *types.VMConfig, storage []*types.StorageConfig, network []*types.NetworkConfig, boot *types.BootConfig) (*types.VM, error) {
	if mock.CreateFunc == nil {
		panic("HypervisorMock.CreateFunc: method is nil but Hypervisor.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		VmID    string
		VmCfg   *types.VMConfig
		Storage []*types.StorageConfig
		Network []*types.NetworkConfig
		Boot    *types.BootConfig
	}{
		Ctx:     ctx,
		VmID:    vmID,
		VmCfg:   vmCfg,
		Storage: storage,
		Network: network,
		Boot:    boot,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, vmID, vmCfg, storage, network, boot)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedHypervisor.CreateCalls())
func (mock *HypervisorMock) CreateCalls() []struct {
	Ctx     context.Context
	VmID    string
	VmCfg   *types.VMConfig
	Storage []*types.StorageConfig
	Network []*types.NetworkConfig
	Boot    *types.BootConfig
} {
	var calls []struct {
		Ctx     context.Context
		VmID    string
		VmCfg   *types.VMConfig
		Storage []*types.StorageConfig
		Network []*types.NetworkConfig
		Boot    *types.BootConfig
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *HypervisorMock) Delete(ctx context.Context, refs []string, force bool) ([]string, error) {
	if mock.DeleteFunc == nil {
		panic("HypervisorMock.DeleteFunc: method is nil but Hypervisor.Delete was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Refs  []string
		Force bool
	}{
		Ctx:   ctx,
		Refs:  refs,
		Force: force,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, refs, force)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedHypervisor.DeleteCalls())
func (mock *HypervisorMock) DeleteCalls() []struct {
	Ctx   context.Context
	Refs  []string
	Force bool
} {
	var calls []struct {
		Ctx   context.Context
		Refs  []string
		Force bool
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Inspect calls InspectFunc.
func (mock *HypervisorMock) Inspect(ctx context.Context, ref string) (*types.VM, error) {
	if mock.InspectFunc == nil {
		panic("HypervisorMock.InspectFunc: method is nil but Hypervisor.Inspect was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref string
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockInspect.Lock()
	mock.calls.Inspect = append(mock.calls.Inspect, callInfo)
	mock.lockInspect.Unlock()
	return mock.InspectFunc(ctx, ref)
}

// InspectCalls gets all the calls that were made to Inspect.
// Check the length with:
//
//	len(mockedHypervisor.InspectCalls())
func (mock *HypervisorMock) InspectCalls() []struct {
	Ctx context.Context
	Ref string
} {
	var calls []struct {
		Ctx context.Context
		Ref string
	}
	mock.lockInspect.RLock()
	calls = mock.calls.Inspect
	mock.lockInspect.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *HypervisorMock) List(contextMoqParam context.Context) ([]*types.VM, error) {
	if mock.ListFunc == nil {
		panic("HypervisorMock.ListFunc: method is nil but Hypervisor.List was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(contextMoqParam)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedHypervisor.ListCalls())
func (mock *HypervisorMock) ListCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// RegisterGC calls RegisterGCFunc.
func (mock *HypervisorMock) RegisterGC(orchestrator *gc.Orchestrator) {
	if mock.RegisterGCFunc == nil {
		panic("HypervisorMock.RegisterGCFunc: method is nil but Hypervisor.RegisterGC was just called")
	}
	callInfo := struct {
		Orchestrator *gc.Orchestrator
	}{
		Orchestrator: orchestrator,
	}
	mock.lockRegisterGC.Lock()
	mock.calls.RegisterGC = append(mock.calls.RegisterGC, callInfo)
	mock.lockRegisterGC.Unlock()
	mock.RegisterGCFunc(orchestrator)
}

// RegisterGCCalls gets all the calls that were made to RegisterGC.
// Check the length with:
//
//	len(mockedHypervisor.RegisterGCCalls())
func (mock *HypervisorMock) RegisterGCCalls() []struct {
	Orchestrator *gc.Orchestrator
} {
	var calls []struct {
		Orchestrator *gc.Orchestrator
	}
	mock.lockRegisterGC.RLock()
	calls = mock.calls.RegisterGC
	mock.lockRegisterGC.RUnlock()
	return calls
}

// Restore calls RestoreFunc.
func (mock *HypervisorMock) Restore(ctx context.Context, vmRef string, vmCfg *types.VMConfig, snapshot io.Reader) (*types.VM, error) {
	if mock.RestoreFunc == nil {
		panic("HypervisorMock.RestoreFunc: method is nil but Hypervisor.Restore was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		VmRef    string
		VmCfg    *types.VMConfig
		Snapshot io.Reader
	}{
		Ctx:      ctx,
		VmRef:    vmRef,
		VmCfg:    vmCfg,
		Snapshot: snapshot,
	}
	mock.lockRestore.Lock()
	mock.calls.Restore = append(mock.calls.Restore, callInfo)
	mock.lockRestore.Unlock()
	return mock.RestoreFunc(ctx, vmRef, vmCfg, snapshot)
}

// RestoreCalls gets all the calls that were made to Restore.
// Check the length with:
//
//	len(mockedHypervisor.RestoreCalls())
func (mock *HypervisorMock) RestoreCalls() []struct {
	Ctx      context.Context
	VmRef    string
	VmCfg    *types.VMConfig
	Snapshot io.Reader
} {
	var calls []struct {
		Ctx      context.Context
		VmRef    string
		VmCfg    *types.VMConfig
		Snapshot io.Reader
	}
	mock.lockRestore.RLock()
	calls = mock.calls.Restore
	mock.lockRestore.RUnlock()
	return calls
}

// Snapshot calls SnapshotFunc.
func (mock *HypervisorMock) Snapshot(ctx context.Context, ref string) (*types.SnapshotConfig, io.ReadCloser, error) {
	if mock.SnapshotFunc == nil {
		panic("HypervisorMock.SnapshotFunc: method is nil but Hypervisor.Snapshot was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref string
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockSnapshot.Lock()
	mock.calls.Snapshot = append(mock.calls.Snapshot, callInfo)
	mock.lockSnapshot.Unlock()
	return mock.SnapshotFunc(ctx, ref)
}

// SnapshotCalls gets all the calls that were made to Snapshot.
// Check the length with:
//
//	len(mockedHypervisor.SnapshotCalls())
func (mock *HypervisorMock) SnapshotCalls() []struct {
	Ctx context.Context
	Ref string
} {
	var calls []struct {
		Ctx context.Context
		Ref string
	}
	mock.lockSnapshot.RLock()
	calls = mock.calls.Snapshot
	mock.lockSnapshot.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *HypervisorMock) Start(ctx context.Context, refs []string) ([]string, error) {
	if mock.StartFunc == nil {
		panic("HypervisorMock.StartFunc: method is nil but Hypervisor.Start was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Refs []string
	}{
		Ctx:  ctx,
		Refs: refs,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(ctx, refs)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedHypervisor.StartCalls())
func (mock *HypervisorMock) StartCalls() []struct {
	Ctx  context.Context
	Refs []string
} {
	var calls []struct {
		Ctx  context.Context
		Refs []string
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *HypervisorMock) Stop(ctx context.Context, refs []string) ([]string, error) {
	if mock.StopFunc == nil {
		panic("HypervisorMock.StopFunc: method is nil but Hypervisor.Stop was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Refs []string
	}{
		Ctx:  ctx,
		Refs: refs,
	}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	return mock.StopFunc(ctx, refs)
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedHypervisor.StopCalls())
func (mock *HypervisorMock) StopCalls() []struct {
	Ctx  context.Context
	Refs []string
} {
	var calls []struct {
		Ctx  context.Context
		Refs []string
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}

// Type calls TypeFunc.
func (mock *HypervisorMock) Type() string {
	if mock.TypeFunc == nil {
		panic("HypervisorMock.TypeFunc: method is nil but Hypervisor.Type was just called")
	}
	callInfo := struct{}{}
	mock.lockType.Lock()
	mock.calls.Type = append(mock.calls.Type, callInfo)
	mock.lockType.Unlock()
	return mock.TypeFunc()
}

// TypeCalls gets all the calls that were made to Type.
// Check the length with:
//
//	len(mockedHypervisor.TypeCalls())
func (mock *HypervisorMock) TypeCalls() []struct{} {
	var calls []struct{}
	mock.lockType.RLock()
	calls = mock.calls.Type
	mock.lockType.RUnlock()
	return calls
}

// Ensure, that DirectMock does implement hypervisor.Direct.
// If this is not the case, regenerate this file with moq.
var _ hypervisor.Direct = &DirectMock{}

// DirectMock is a mock implementation of hypervisor.Direct.
//
//	func TestSomethingThatUsesDirect(t *testing.T) {
//
//		// make and configure a mocked hypervisor.Direct
//		mockedDirect := &DirectMock{
//			DirectCloneFunc: func(ctx context.Context, vmID string, vmCfg *types.VMConfig, networkConfigs []*types.NetworkConfig, snapshotConfig *types.SnapshotConfig, srcDir string) (*types.VM, error) {
//				panic("mock out the DirectClone method")
//			},
//			DirectRestoreFunc: func(ctx context.Context, vmRef string, vmCfg *types.VMConfig, srcDir string) (*types.VM, error) {
//				panic("mock out the DirectRestore method")
//			},
//		}
//
//		// use mockedDirect in code that requires hypervisor.Direct
//		// and then make assertions.
//
//	}
type DirectMock struct {
	// DirectCloneFunc mocks the DirectClone method.
	DirectCloneFunc func(ctx context.Context, vmID string, vmCfg *types.VMConfig, networkConfigs []*types.NetworkConfig, snapshotConfig *types.SnapshotConfig, srcDir string) (*types.VM, error)

	// DirectRestoreFunc mocks the DirectRestore method.
	DirectRestoreFunc func(ctx context.Context, vmRef string, vmCfg *types.VMConfig, srcDir string) (*types.VM, error)

	// calls tracks calls to the methods.
	calls struct {
		// DirectClone holds details about calls to the DirectClone method.
		DirectClone []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VmID is the vmID argument value.
			VmID string
			// VmCfg is the vmCfg argument value.
			VmCfg *types.VMConfig
			// NetworkConfigs is the networkConfigs argument value.
			NetworkConfigs []*types.NetworkConfig
			// SnapshotConfig is the snapshotConfig argument value.
			SnapshotConfig *types.SnapshotConfig
			// SrcDir is the srcDir argument value.
			SrcDir string
		}
		// DirectRestore holds details about calls to the DirectRestore method.
		DirectRestore []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VmRef is the vmRef argument value.
			VmRef string
			// VmCfg is the vmCfg argument value.
			VmCfg *types.VMConfig
			// SrcDir is the srcDir argument value.
			SrcDir string
		}
	}
	lockDirectClone   sync.RWMutex
	lockDirectRestore sync.RWMutex
}

// DirectClone calls DirectCloneFunc.
func (mock *DirectMock) DirectClone(ctx context.Context, vmID string, vmCfg *types.VMConfig, networkConfigs []*types.NetworkConfig, snapshotConfig *types.SnapshotConfig, srcDir string) (*types.VM, error) {
	if mock.DirectCloneFunc == nil {
		panic("DirectMock.DirectCloneFunc: method is nil but Direct.DirectClone was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		VmID           string
		VmCfg          *types.VMConfig
		NetworkConfigs []*types.NetworkConfig
		SnapshotConfig *types.SnapshotConfig
		SrcDir         string
	}{
		Ctx:            ctx,
		VmID:           vmID,
		VmCfg:          vmCfg,
		NetworkConfigs: networkConfigs,
		SnapshotConfig: snapshotConfig,
		SrcDir:         srcDir,
	}
	mock.lockDirectClone.Lock()
	mock.calls.DirectClone = append(mock.calls.DirectClone, callInfo)
	mock.lockDirectClone.Unlock()
	return mock.DirectCloneFunc(ctx, vmID, vmCfg, networkConfigs, snapshotConfig, srcDir)
}

// DirectCloneCalls gets all the calls that were made to DirectClone.
// Check the length with:
//
//	len(mockedDirect.DirectCloneCalls())
func (mock *DirectMock) DirectCloneCalls() []struct {
	Ctx            context.Context
	VmID           string
	VmCfg          *types.VMConfig
	NetworkConfigs []*types.NetworkConfig
	SnapshotConfig *types.SnapshotConfig
	SrcDir         string
} {
	var calls []struct {
		Ctx            context.Context
		VmID           string
		VmCfg          *types.VMConfig
		NetworkConfigs []*types.NetworkConfig
		SnapshotConfig *types.SnapshotConfig
		SrcDir         string
	}
	mock.lockDirectClone.RLock()
	calls = mock.calls.DirectClone
	mock.lockDirectClone.RUnlock()
	return calls
}

// DirectRestore calls DirectRestoreFunc.
func (mock *DirectMock) DirectRestore(ctx context.Context, vmRef string, vmCfg *types.VMConfig, srcDir string) (*types.VM, error) {
	if mock.DirectRestoreFunc == nil {
		panic("DirectMock.DirectRestoreFunc: method is nil but Direct.DirectRestore was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		VmRef  string
		VmCfg  *types.VMConfig
		SrcDir string
	}{
		Ctx:    ctx,
		VmRef:  vmRef,
		VmCfg:  vmCfg,
		SrcDir: srcDir,
	}
	mock.lockDirectRestore.Lock()
	mock.calls.DirectRestore = append(mock.calls.DirectRestore, callInfo)
	mock.lockDirectRestore.Unlock()
	return mock.DirectRestoreFunc(ctx, vmRef, vmCfg, srcDir)
}

// DirectRestoreCalls gets all the calls that were made to DirectRestore.
// Check the length with:
//
//	len(mockedDirect.DirectRestoreCalls())
func (mock *DirectMock) DirectRestoreCalls() []struct {
	Ctx    context.Context
	VmRef  string
	VmCfg  *types.VMConfig
	SrcDir string
} {
	var calls []struct {
		Ctx    context.Context
		VmRef  string
		VmCfg  *types.VMConfig
		SrcDir string
	}
	mock.lockDirectRestore.RLock()
	calls = mock.calls.DirectRestore
	mock.lockDirectRestore.RUnlock()
	return calls
}
